Replace marketing with penguins data in clustering chapter
UBC-DSCI/introduction-to-datascience pull request #144
Opened 2021-05-11 18:46 UTC by leem44

@ttimbers @trevorcampbell Please take a look when you can! Let me know any changes I should make! 
- Addressing #116 (will do inference changes in separate branch) specifically: 

- @leem44 I think the Palmer penguins data (with the species label removed) for bill depth vs bill length would be a nice example of using clustering to discover subgroups in data. You could even add the labels back in at the very end to show that the clustering procedure found meaningful subgroups (although you'd have to be very careful to mention that if we had labels in the first place, we wouldn't need to cluster). Maybe you can spin it as "ok based on your clustering exploration you send out some scientists and they identify 3 species, here they are!"
_Originally posted by @trevorcampbell in https://github.com/UBC-DSCI/introduction-to-datascience/issues/116#issuecomment-829429597_

I decided not to show the labels of the data at the end since I thought students might be confused, but let me know if you feel strongly otherwise

- replaced marketing example with penguins data 
- updated writing, code and images relevant to new data 
- updated references.bib

2021-05-12 16:09 UTC, ttimbers commented
If we stick with this example for the clustering chapter, I hope we can make the narrative very clear that this is different than classification. In the course, we currently make a huge emphasis that in clustering we have no labels, which is why we must cluster - which is good and important, and I think we need to keep doing this. So my worry with this data set is that we do have labels... So I wonder if that we are not extremely careful, we might send students the wrong message to the students using such a data set for our initial clustering example...

2021-05-12 16:26 UTC, leem44 commented
> If we stick with this example for the clustering chapter, I hope we can make the narrative very clear that this is different than classification. In the course, we currently make a huge emphasis that in clustering we have no labels, which is why we must cluster - which is good and important, and I think we need to keep doing this. So my worry with this data set is that we do have labels... So I wonder if that we are not extremely careful, we might send students the wrong message to the students using such a data set for our initial clustering example...

Yes, I agree with you here!  I removed the labels from the data and don't make any mention of them in the narrative at all.   All I say is "The data set has been modified for use in this chapter" but I don't mention there are any species labels in the data. Let me know what you think here!

2021-05-12 17:45 UTC, trevorcampbell requested changes

2021-05-12 17:45 UTC, trevorcampbell commented on 09-clustering.Rmd
> +$$S^2 = \left((x_1 - \mu_x)^2 + (y_1 - \mu_y)^2\right) + \left((x_2 - \mu_x)^2 + (y_2 - \mu_y)^2\right) +\left((x_3 - \mu_x)^2 + (y_3 - \mu_y)^2\right) \left((x_4 - \mu_x)^2 + (y_4 - \mu_y)^2\right).
This equation is too long for rendering on a single line (at least in my web browser)

2021-05-12 17:45 UTC, trevorcampbell commented on 09-clustering.Rmd
> +For example, in the penguin data example, our initialization might look like this:
i like the color scheme, but maybe it's not great for colorblind vision? pass these images through a colorblind filter to see what they look like, and if needed change to a different scheme

2021-05-12 17:45 UTC, trevorcampbell commented on 09-clustering.Rmd
>  ranging from 1 to 9.
the figure here doesn't look right. the means don't appear to be positioned correctly within their clusters

2021-05-12 17:45 UTC, trevorcampbell commented on 09-clustering.Rmd
>  ```
this fenced code block needs the "r" syntax highlighting

2021-05-12 17:45 UTC, trevorcampbell commented on references.bib
> +    title = {palmerpenguins: Palmer Archipelago (Antarctica) penguin data},
This gets typeset as `Palmerpenguins` in the textbook, it should be `palmerpenguins`. You can achieve this by adding curly braces around anything you want to preserve the formatting of, e.g.

```
    title = {{palmerpenguins}: Palmer Archipelago (Antarctica) penguin data},
```

2021-05-13 17:54 UTC, leem44 commented
Thanks for the comments @trevorcampbell! Merging branch!

2021-05-13 17:54 UTC, merged